// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc5506.Steamworks;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.AnalogGyro;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.VictorSP;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
	public static SpeedController driveTrainDriveLeft;
	public static SpeedController driveTrainDriveRight;
	public static AnalogGyro driveTrainGyro;
	public static SpeedController climberClimber;

	public static void init() {
		driveTrainDriveLeft = new VictorSP(1);
		LiveWindow.addActuator("DriveTrain", "DriveLeft", (VictorSP) driveTrainDriveLeft);

		driveTrainDriveRight = new VictorSP(2);
		LiveWindow.addActuator("DriveTrain", "DriveRight", (VictorSP) driveTrainDriveRight);

		driveTrainGyro = new AnalogGyro(0);
		LiveWindow.addSensor("DriveTrain", "Gyro", driveTrainGyro);
		driveTrainGyro.setSensitivity(0.007);
		climberClimber = new Spark(3);
		LiveWindow.addActuator("Climber", "Climber", (Spark) climberClimber);
	}
}
