// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5506.Steamworks.commands;

import org.usfirst.frc5506.Steamworks.Robot;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class Auto extends CommandGroup {
	public Command selectedCommand = null;
	
	public Auto() {
		this(false);
	}
	
    public Auto(boolean skipGear) {
    	// this should mean that conveyer is always safe
    	if (selectedCommand != null) {
    		addParallel(new Routine("SafeReset"));
    		selectedCommand.start();
    	}
    	if (skipGear) {
    		/*switch(Robot.starting) {
    			case(1):
    			case(3):
    				addSequential(new Routine("/curveleft:-0.6:2;curveright:-0.6:2;driveright:-0.6:1;stop"));
    				break;
    			case(2):
    			default:
    				addSequential(new Routine("/curveleft:-0.7;1;curveright:-0.7:1;stop;turnto:45;/curveleft:-0.8:2;curveleft:-0.8:2;turnto:0;/curveleft:-0.8:2;curveright:-0.8:2;stop"));
    				break;
    		}*/
    		addSequential(new Surge());
    	} else {
    		switch(Robot.starting) {
    			case(1):
    			case(3):
    				addSequential(new Routine("/curveleft:-0.5:1;curveright:-0.5:1;stop"));
    				addSequential(new Gear(true));
    				break;
    			case(2):
    			default:
    				addSequential(new Gear(true));
    				break;
    		}
    	}
    } 
}
