// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5506.Steamworks.commands;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 * See RoutineCommand.java for documentation.
 */
public class Routine extends CommandGroup {
    public Routine(String script) {
    	String[] commands = script.toLowerCase().split(";");
    	for (int i = 0; i < commands.length; i++) {
    		String j = commands[i];
    		if (j.charAt(0) == '/') {
    			addParallel(getCommand(j.substring(1)));
    		} else
    			addSequential(getCommand(j));
    	}
    }
    
    // use for special subroutines that aren't in RoutineCommand
    public Command getCommand(String command) {
    	switch(command) {
    		case("gear"):
    			return new Gear();
    		case("safereset"):
    			return new Routine("BumpConveyer;ResetConveyer");
    		default:
    			return new RoutineCommand(command);
    	}
    }
}
