// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5506.Steamworks.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc5506.Steamworks.Robot;

/**
 *
 */
public class Teleop extends Command {
	
	// "true" removes tank drive functionality, and switches to arcade drive via j1
	public boolean j1arcade = true;
	
	public boolean conveyorPos = false;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
public Teleop() {
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveTrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	if (j1arcade){
    		// why do I have to invert these? idk.
    		double x = Robot.oi.getFunctionJoystick().getX() / 2;
    		double y = Robot.oi.getFunctionJoystick().getY() / 2;
    		
    		Robot.driveTrain.driveLeft(y + x);
    		Robot.driveTrain.driveRight(y - x);

			if (Robot.conveyor.getSwitch())
				conveyorPos = false;
    		if (Robot.oi.getFunctionJoystick().getRawButton(11) && !Robot.conveyor.getSwitch()) {
    			Robot.conveyor.set(conveyorPos ? -0.5 : -1);
    			if (Robot.conveyor.getSwitch())
    				conveyorPos = true;
    		} else if (Robot.oi.getFunctionJoystick().getRawButton(12))
    			Robot.conveyor.set(1);
    		else
    			Robot.conveyor.set(0);
    	} else {
	    	//left axis = 1, right axis = 5
	    	double leftSpeed = Robot.oi.getDriverJoystick().getRawAxis(1);
	    	double rightSpeed = Robot.oi.getDriverJoystick().getRawAxis(5);
	    	
	        //z axis
	    	double conveyorSpeed = Robot.oi.getDriverJoystick().getZ(); //HEYYYYY KIIIOOOONN
	
	    	Robot.driveTrain.driveLeft(leftSpeed);
	        Robot.driveTrain.driveRight(rightSpeed);
	        
	        Robot.conveyor.set(conveyorSpeed);
    	}
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.driveTrain.driveLeft(0);
    	Robot.driveTrain.driveRight(0);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	
    }
}
